### ISSUE TITLE
False negative WARNING for __construct() method for PHP8.1

### ISSUE THREAD

**Issue by jakwinkler** [mrm-commerce/magento-coding-standard-phpcs#1]
After fixing the code for PHP8.1
![image](https://user-images.githubusercontent.com/4256191/213680605-cd464a69-91f0-451f-8f9c-1aa27936dc2d.png)

The rules return the wrong message
![image](https://user-images.githubusercontent.com/4256191/213680500-d2d8859b-bb45-4ec5-8ef7-227a6e97fae0.png)

This code should pass static code analysis :-)

**Comment by bgorski** [comment]
@qsolutions-pl the rule that fails is Magento2.CodeAnalysis.EmptyBlock. Can you check your composer.lock file and let me know what's the version of the `magento/magento-coding-standard` package? The MRM Coding Standard doesn't enforce any particular version, instead relying on what can be installed on your project (which is usually limited by your version of webonyx/graphql-php, which is a dependency for the M2 coding standard package). Chances are you have version 6 of the M2 coding standard, and you would need at least 25 (the important piece of code is here: https://github.com/magento/magento-coding-standard/blob/v25/Magento2/Sniffs/CodeAnalysis/EmptyBlockSniff.php#L40).

Can you run the following command, check if it upgraded your m2 coding standard package and check if you still encounter the issue?

`composer require --dev --with-all-dependencies mrm-commerce/magento-coding-standard-phpcs:3.0.1-RC `

You can of course use 3.0.0 if you don't want 3.0.1-RC1 but I strongly recommend that RC version since it also fixes an issue with xml files broken by some PSR12 rule.

**Comment by jakwinkler** [comment]
the problem was wrong version of magento 2 coding standards in the project
